# Generated by Django 3.0.3 on 2021-04-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('CSA', 'CSA'), ('CSB', 'CSB'), ('ITA', 'ITA'), ('ITB', 'ITB'), ('ETCA', 'ETCA'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH')], max_length=100)),
                ('enrollment', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
