# Generated by Django 3.2 on 2021-04-30 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20210430_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll_Data',
            fields=[
                ('sheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enroll_datasheet', models.FileField(upload_to='enroll_datasheets')),
            ],
        ),
    ]
