# Generated by Django 3.2 on 2021-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_enroll_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CIVIENG_FT', 'CIVIENG_FT'), ('COMPENG_FT', 'COMPENG_FT'), ('ECIENG_FT', 'ECIENG_FT'), ('ECTELEG_FT', 'ECTELEG_FT'), ('ITENG_FT', 'ITENG_FT'), ('MECHENG_FT', 'MECHENG_FT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
