# Generated by Django 3.2 on 2021-05-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_marksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.student'),
        ),
    ]
