# Generated by Django 3.2 on 2021-05-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_marksheet_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='marksheet_URL',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.student'),
        ),
    ]
