# Generated by Django 3.2 on 2021-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20210502_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='receipt_URL',
            field=models.JSONField(null=True),
        ),
    ]
