# Generated by Django 3.2 on 2021-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_marksheet_receipt_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('sub_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=5)),
                ('theory_credit', models.IntegerField()),
                ('practical_credit', models.IntegerField()),
            ],
        ),
    ]
